### ISSUE TITLE
Hi, may I get your source code for your great project?

### ISSUE THREAD

**Issue by wangtengyi5555** [surrealyz/pdfclassifier#1]
I've developed a new evasion attack method and am willing to choose your models as targets. However, When I followed the website in your essay, I just found nothing here in your repository.

May I have your source code please?

Thank you very much.

我最近开发了一个新的自动逃逸攻击，发现你们的模型非常有趣，希望能够拥有你们的源码进行研究看是否我的方法取得了更好的效果和效率。非常感谢。

**Comment by surrealyz** [comment]
Thank you for your interest in our project. We are working on releasing the source code and it will be available soon.

**Comment by wangtengyi5555** [comment]
Thank you very much for letting me know.

Good night

**Comment by surrealyz** [comment]
We have open sourced our models, training code, and attack code.
