### ISSUE TITLE
dataset password

### ISSUE THREAD

**Issue by lyqssb** [surrealyz/pdfclassifier#2]
Hi ,I'm trying to get the results as your paper said. And I tried to download the dataset on [http://contagiodump.blogspot.com/2013/03/16800-clean-and-11960-malicious-files.html](url). This dataset needs password ,and I don't know. If you know the password or you know other way to get this dataset, please let me know! thank you very much!

**Comment by surrealyz** [comment]
See the right side of the contagio webpage: "Zip files passwords: Contact me via email (see my profile) for the passwords or the password scheme." The dataset owner's email is MilaParkour@gmail.com

You can also email me at surrealyz@gmail.com and I will forward the password scheme to you.

**Comment by lyqssb** [comment]
Hi！I emailed you! Looking forward to your reply~Thank you！
