### ISSUE TITLE
extract data structure error

### ISSUE THREAD

**Issue by lyqssb** [surrealyz/pdfclassifier#3]
Hi! I met this error when I used the tool you recommended in your papper. The error:[https://github.com/srndic/hidost/issues/6#issue-761210111](url).I don't get response from him. I think maybe you know how to fix this! I have already installed hidost just like they said in their INSTALL.rst[https://github.com/srndic/hidost/blob/master/INSTALL.rst](url). So why the terminal return this error to me? Thank you!

**Comment by surrealyz** [comment]
If you have run the build and make commands, have you tried looking for where the binaries are? For example, under build/? or somewhere in your $PATH?

**Comment by lyqssb** [comment]
I don't know the binaries you mean.These things are under my build/:
>cleowang@ubuntu:~/hidost/build$ ls
CMakeCache.txt  cmake_install.cmake  install_manifest.txt  src
CMakeFiles      hidost               Makefile
 
my PATH :
> cleowang@ubuntu:~/hidost/build$ $PATH
bash: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/java/jdk1.7.0_80/bin:/usr/java/jdk1.7.0_80/jre/bin: No such file or directory

So how could I found binaries and make this tool work?

**Comment by lyqssb** [comment]
I found the error! I didn't notice there is a new src/ under the build/. So I didn't change directory to build/. But I am  still wondering how did you distinguish clean pdf and malware pdf? Have You distinguished them just by their names and .pdf suffix? Then you delete a lot of other format data from the source dataset and get your own bpdfs.txt and mpdfs.txt?

**Comment by surrealyz** [comment]
Glad to know that you fixed it. The malicious and benign datasets are labeled by the contagio dataset. You can put the paths in the mpdfs.txt and bpdfs.txt. I have also provided the extracted feature vectors here https://github.com/surrealyz/pdfclassifier/tree/master/data/traintest_all_500test
