### ISSUE TITLE
gradient attackers 

### ISSUE THREAD

**Issue by lyqssb** [surrealyz/pdfclassifier#4]
Hi! I am trying this command on my gpu server `python gradient_attack.py --method D --model ATAB`. This command could print something like this:`('steps:', 1266, 'adv_acc:', 0.9344262295081968)`,but the program has been running for two days and nights. When I am writing this issue ,it is still running~ And I have already checked my gpu, it looks like this:

> [0] Tesla T4         | 54'C,   0 % | 14540 / 15109 MB | ubuntu1804:python/17341(14533M) gdm:Xorg/1174(4M)

Could you tell me what caused this program to run so slowly? Thank you so much!

**Comment by surrealyz** [comment]
Hi, I'm not sure why your command took so long to run `--method D`. I think the only attack that takes a long time to run is the `unrestricted_gradient_attack` with 200,000 iterations https://github.com/surrealyz/pdfclassifier/blob/master/attack/gradient_attack.py#L108

Maybe you can try to figure out where is the slowest part?
